# Generated by Django 2.0.4 on 2018-04-05 11:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(help_text='The age of the vehicle in years')),
                ('registration_nr', models.CharField(max_length=128)),
                ('max_passengers', models.PositiveIntegerField(help_text='The amount of passengers this vehicle can transport')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True)),
                ('available', models.BooleanField()),
                ('wing_span', models.PositiveIntegerField(help_text='The wing span of the plane in meters')),
                ('requires_copilot', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(help_text='The age of the vehicle in years')),
                ('registration_nr', models.CharField(max_length=128)),
                ('max_passengers', models.PositiveIntegerField(help_text='The amount of passengers this vehicle can transport')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True)),
                ('available', models.BooleanField()),
                ('depth', models.PositiveIntegerField(help_text='The depth of the boat in meters')),
                ('type', models.CharField(choices=[('sail_yacht', 'Sailing yacht'), ('luxery_yacht', 'Delux yacht'), ('cruise_ship', 'Cruise ship')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(help_text='The age of the vehicle in years')),
                ('registration_nr', models.CharField(max_length=128)),
                ('max_passengers', models.PositiveIntegerField(help_text='The amount of passengers this vehicle can transport')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2048, null=True)),
                ('available', models.BooleanField()),
                ('nr_wheels', models.PositiveIntegerField()),
                ('electric', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
